resources:
  provider: s3

server:
  shutdown: immediate

import-files:
  locations: "schedule_34_locations.xlsx"
  serco-prices: "serco_prices.xlsx"
  geo-prices: "geoamey_prices.xlsx"

export-files:
  template: classpath:/spreadsheets/JCP_template.xlsx
